import Head from "next/head";
import { Roboto } from "next/font/google";
import "./globals.css";
import ComponentLayout from "@/components/componentLayout/componentLayout.jsx";

const inter = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href={inter.href} />
      </Head>
      <body className={inter.className}>
        <ComponentLayout>{children}</ComponentLayout>
      </body>
    </html>
  );
}
