import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import ComponentLayout from "@/components/componentLayout/componentLayout.jsx";
import Link from "next/link";

const inter = Roboto
(
  { 
    weight: ['400', '700'],
    subsets: ['latin'],
    display: 'swap',
  });
  
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <ComponentLayout children={children} />      
        </body>
    </html>
  );
}
